#server:
#  port: 0 # dynamically auto-magically assign free port - This will help with Load balancing
          # Having multiple instances of the same service
spring:
#  application:
#    name: spring-cloud-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # unique for each instance