spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

test:
  name: "meaw"