spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: spring-cloud-server
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log